version: '3'
services:
  gatebot:
    build: .
    volumes:
      - ./local.py:/app/config/local.py:ro
    restart: always
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=gatebot
      - POSTGRES_USER=gatebot
      - POSTGRES_DB=gatebot
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata:rw
